### ISSUE TITLE
Components not working in MDX

### ISSUE THREAD

**Issue by danteissaias** [primer/components#401] opened 2019-02-11 01:15 UTC
When navigating to a component example the MDX Box displays the following error:

`ReferenceError: Button is not defined`

**Comment by emplums** [comment] 2019-02-11 18:13
Hey @danteissaias can you provide a bit more context? Are you using MDX in your project or are you referring to the MDX snippets on our docs site?

**Comment by emplums** [comment] 2019-02-11 18:15
We're using MDX for our docs site and it seems to be working fine, are you sure that you've imported the components in your app.js and properly passed them to your MDXProvider, like we've done here? https://github.com/primer/components/blob/master/pages/_app.js#L67

**Comment by danteissaias** [comment] 2019-02-11 22:08
I simply just cloned this repository, ran `npm run dev` and was getting that error. Very strange.

**Comment by emplums** [comment] 2019-02-12 18:05
@danteissaias Huh, I am not able to reproduce on my end. Is it possible that `npm install` didn't get run? Are you still able to reproduce on your end?

**Comment by danteissaias** [comment] 2019-02-12 18:36
I am running this on OSX could that be an issue. I'll test it again now?

**Comment by emplums** [comment] 2019-02-19 07:34
Hey @danteissaias any luck getting the docs to run correctly?

**Comment by emplums** [comment] 2019-02-25 22:02
I'm going to close this one for now but let me know if you're still having issues!

**Closed by emplums** 2019-02-25 22:02 UTC
Labels: ds-reviewed
