### ISSUE TITLE
Theming Audit + Color Modes support

### ISSUE THREAD

**Issue by emplums** [primer/components#639] opened 2019-10-31 17:52 UTC
We've got lots of color variables referencing the theme like so: `color: ${get('colors.gray.8')` instead of referencing contextual variables like `text-grey`, in fact, we don't even have contextual variables in our theme yet!

### To do:
- [ ] Update theme with contextual variables
- [ ] Connect with @simurai and @joelhawksley on how primitives needs to be structured to use in each project
- [ ] Move theme to primer primitives
- [ ] import primer primitives theme
- [ ] export `theme` from primitives?
- [ ] update theme calls in the code
- [ ] test theming?!

**Comment by BinaryMuse** [comment] 2020-02-21 23:53
One of the things that we noticed was that some Jest snapshots include a `theme` attribute on DOM nodes. We originally thought this was a bug in the implementation of those components, where we were incorrectly pulling `theme` out of props before we spread them onto a DOM node.

However, upon investigation, it seems this is all caused by the following testing pattern:

```javascript
  it('renders the given "as" prop', () => {
    const Type = props => <b {...props} />
    expect(render(<SomeComponent as={Type} />)).toMatchSnapshot()
  })
```

Because `Type` in each of these tests simply passes *all* props to the DOM node, the DOM node ends up including the `theme` prop.

One solution might be to change the test to something like:

```diff
diff --git a/src/__tests__/UnderlineNavLink.js b/src/__tests__/UnderlineNavLink.js
index ece0cdc8..726bb79b 100644
--- a/src/__tests__/UnderlineNavLink.js
+++ b/src/__tests__/UnderlineNavLink.js
@@ -1,10 +1,11 @@
 import React from 'react'
 import UnderlineNav from '../UnderlineNav'
-import {render} from '../utils/testing'
+import {render, componentExpectations} from '../utils/testing'
 import {render as HTMLRender, cleanup} from '@testing-library/react'
 import {axe, toHaveNoViolations} from 'jest-axe'
 import 'babel-polyfill'
 expect.extend(toHaveNoViolations)
+expect.extend(componentExpectations)
 
 describe('UnderlineNav.Link', () => {
   it('renders an <a> by default', () => {
@@ -23,8 +24,9 @@ describe('UnderlineNav.Link', () => {
   })
 
   it('renders the given "as" prop', () => {
-    const Type = props => <b {...props} />
-    expect(render(<UnderlineNav.Link as={Type} />)).toMatchSnapshot()
+    expect(UnderlineNav.Link).toRespectAsProp()
   })
 
   it('respects the "selected" prop', () => {
diff --git a/src/utils/testing.js b/src/utils/testing.js
index 0fc519a0..47521d0d 100644
--- a/src/utils/testing.js
+++ b/src/utils/testing.js
@@ -11,6 +11,64 @@ const readFile = promisify(require('fs').readFile)
 
 enzyme.configure({adapter: new Adapter()})
 
+export const componentExpectations = {
+  toRespectAsProp(ComponentClass) {
+    const Mock = jest.fn(() => <div />)
+    render(<ComponentClass as={Mock} />)
+    expect(Mock.mock.calls.length).toEqual(1)
+    if (Mock.mock.calls.length === 1) {
+      return {
+        pass: true,
+        message: () => `expected component ${ComponentClass} not to respect 'as' prop`
+      }
+    } else {
+      return {
+        pass: false,
+        message: () => `expected component ${ComponentClass} to respect 'as' prop`
+      }
+    }
+  }
+}
+
 export function mount(component) {
   return enzyme.mount(component)
 }
```

In case it ends up being useful, I also worked on an assertion to ensure `theme` doesn't make it to the DOM by accident:

```javascript
function findNodeWithTheme({type, props, children}, path = []) {
  if (props.theme) {
    return path.concat([type])
  }

  if (children) {
    for (let i = 0; i < children.length; i++) {
      const childWithTheme = findNodeWithTheme(children[i], path.concat([type, i]))
      if (childWithTheme) {
        return childWithTheme
      }
    }
  }

  return null
}

export const componentExpectations = {
  toProperlyHandleTheme(element) {
    const rendered = render(React.cloneElement(element, {theme: {fakeTheme: true}}))
    const nodeWithTheme = findNodeWithTheme(rendered)
    const passed = nodeWithTheme === null

    if (passed) {
      return {
        message: () => `expected element ${element.type} to render theme prop to the DOM`,
        pass: true
      }
    } else {
      return {
        message: () =>
          `expected element ${element.type} not to render theme prop to the DOM but found theme at ${nodeWithTheme.join(
            '.'
          )}`,
        pass: false
      }
    }
  }
}
```

**Comment by colebemis** [comment] 2021-03-04 20:16
Closing in favor of this [theming epic issue](https://github.com/github/design-systems/issues/1219)

**Closed by colebemis** 2021-03-04 20:16 UTC
Labels: effort: high, enhancement, minor release
